force-app/main/default/objects/Sentry_Active_Config__c/Sentry_Active_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>The active Configuration to use for Sentry</description>
    <label>Sentry Active Config</label>
</CustomObject>

force-app/main/default/objects/Sentry_Active_Config__c/fields/Environment_Name__c.field-meta.xml
<CustomField>
    <fullName>Environment_Name__c</fullName>
    <description>The name of the environment to use in place of the calculated environment from the URL.</description>
    <label>Environment Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sentry_Active_Config__c/fields/IsDebug__c.field-meta.xml
<CustomField>
    <fullName>IsDebug__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is Debug Enabled?</description>
    <label>Debug</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sentry_Active_Config__c/fields/IsIssueCreationDisabled__c.field-meta.xml
<CustomField>
    <fullName>IsIssueCreationDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is Issue Creation Disabled?</description>
    <label>Issue Creation Disabled?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sentry_Active_Config__c/fields/Sentry_Config__c.field-meta.xml
<CustomField>
    <fullName>Sentry_Config__c</fullName>
    <defaultValue>&quot;Default&quot;</defaultValue>
    <description>The DeveloperName of the Sentry_Config__mdt entry to use for configuration.</description>
    <label>Sentry Config DeveloperName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SentryTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an org are executed whenever Apex code is deployed
 * to a production org to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production org. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the org size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@IsTest
public with sharing class SentryTest {
    @IsTest
    static void Record() {
        Exception ex;

        Test.setMock(HttpCalloutMock.class, new Sentry_ApiMock());

        Sentry_TestingController controller = new Sentry_TestingController();

        Sentry_Active_Config__c config = Sentry_Active_Config__c.getOrgDefaults();
        config.IsIssueCreationDisabled__c = false;
        config.IsDebug__c = true;
        config.Sentry_Config__c = 'Test';
        config.Environment_Name__c = 'Test';
        insert config;

        Test.startTest();

        try {
            controller.triggerCapturedException();
        } catch (Exception e) {
            ex = e;
        }

        Test.stopTest();

        System.assertNotEquals(null, ex);
    }
    
    @IsTest
    static void RecordwithCustomException() 
    {
        Exception ex;

        Test.setMock(HttpCalloutMock.class, new Sentry_ApiMock());

        Sentry_TestingController controller = new Sentry_TestingController();

        Sentry_Active_Config__c config = Sentry_Active_Config__c.getOrgDefaults();
        config.IsIssueCreationDisabled__c = false;
        config.IsDebug__c = true;
        config.Sentry_Config__c = 'Test';
        config.Environment_Name__c = 'Test';
        insert config;

        Test.startTest();
        controller.triggerCustomException();
        Test.stopTest();

        System.assertEquals(null, ex);
    }
    
    @IsTest
    static void RecordCustomExceptionWithoutSendingToSentry() 
    {
        Exception ex;

        Test.setMock(HttpCalloutMock.class, new Sentry_ApiMock());

        Sentry_TestingController controller = new Sentry_TestingController();

        Sentry_Active_Config__c config = Sentry_Active_Config__c.getOrgDefaults();
        config.IsIssueCreationDisabled__c = true;
        config.IsDebug__c = true;
        config.Sentry_Config__c = 'Test';
        config.Environment_Name__c = 'Test';
        insert config;

        Test.startTest();
        controller.triggerCustomException();
        Test.stopTest();

        System.assertEquals(null, ex);
    }
}