force-app/main/default/objects/Sentry_Error__e/Sentry_Error__e.object-meta.xml
<CustomObject>
    <label>Sentry Error</label>
    <pluralLabel>Sentry Errors</pluralLabel>
</CustomObject>

force-app/main/default/objects/Sentry_Error__e/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <description>The serialized version of the Sentry_Error object.</description>
    <label>Content</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/Sentry.cls
public with sharing class Sentry {
  public static void record(Exception e) {
    Sentry_Event err = convertExceptiontoError(e);
    sendEvent(err);
  }

  public static void record(
    String issueTitle,
    Exception e,
    List<Sentry_LogMessage> lExtraMessages
  ) {
    Sentry_Event err = convertExceptionToError(issueTitle, e, lExtraMessages);
    sendEvent(err);
  }

  private static Sentry_Event convertExceptionToError(Exception e) {
    return new Sentry_Event(e);
  }

  private static Sentry_Event convertExceptionToError(
    String issueTitle,
    Exception e,
    List<Sentry_LogMessage> lExtraMessages
  ) {
    return new Sentry_Event(issueTitle, e, lExtraMessages);
  }

  private static void sendEvent(Sentry_Event err) {
    Sentry_Log.logSentry(
      '[Sentry.sendEvent] event: ' + JSON.serializePretty(err)
    );
    Sentry_Log.logSentry(
      '[Sentry.sendEvent] message: ' + JSON.serializePretty(err.toMessage())
    );

    Sentry_Error__e e = new Sentry_Error__e(
      Content__c = JSON.serialize(err.toMessage())
    );
    EventBus.publish(e);
  }
}